language: rust
cache: cargo
rust:
  - stable

addons:
  apt:
    packages:
    - texinfo
    - libgif-dev
    - libxpm-dev

env:
  # Ensure that we build without warnings.
  - CARGO_FLAGS="--features 'strict'"

services:
  - docker

script:
  # https://github.com/travis-ci/travis-ci/issues/5770#issuecomment-197771661
  - "docker run -i -v \"${PWD}:/remacs\" toopher/centos-i386:centos6 /bin/bash -c \"linux32 --32bit i386 /remacs/.32_bit_build.sh\""
  # # Configure Emacs for building
  # - ./autogen.sh
  # - ./configure
  # - make -j 3

  # - make check || echo 'make check failed'

notifications:
  fast_finish: true
  email: false

matrix:
  allow_failures:
    - rust: nightly
